#!/usr/bin/env python3
"""Generate the Wave 1–3 priority slug backlog for UAO SEO/AEO."""

from __future__ import annotations

import csv
from pathlib import Path

OUT = Path(__file__).with_name("priority-slugs.csv")
FIELDS = [
    "wave",
    "type",
    "slug",
    "title",
    "audience",
    "conversion",
    "priority",
    "status",
    "notes",
]


def row(**kwargs) -> dict:
    base = {k: "" for k in FIELDS}
    base.update(kwargs)
    return base


def main() -> None:
    rows: list[dict] = []

    wave1 = [
        ("directory", "directory", "The Universal Owner Directory", "both", "advertiser-call"),
        ("directory/legal", "directory", "Legal counsel for asset owners", "both", "advertiser-call"),
        ("directory/accounting", "directory", "Accounting and tax for asset owners", "both", "advertiser-call"),
        ("directory/technology", "directory", "Technology for asset owners", "both", "advertiser-call"),
        ("directory/investment-banking", "directory", "Investment banking for asset owners", "both", "advertiser-call"),
        ("how-pension-funds-retain-counsel", "explainer", "How pension funds retain counsel", "both", "advertiser-call"),
        ("family-offices-as-universal-owners", "explainer", "Family offices as universal owners", "both", "brief"),
        ("what-does-a-family-office-cio-do", "explainer", "What does a family-office CIO do?", "allocator", "brief"),
        (
            "careers/intelligence/relocating-for-an-asset-owner-role",
            "careers",
            "Relocating for an asset-owner role",
            "both",
            "careers-alert",
        ),
        ("careers/cities/abu-dhabi", "city", "Relocating to Abu Dhabi", "both", "careers-alert"),
        ("careers/cities/singapore", "city", "Relocating to Singapore", "both", "careers-alert"),
        ("careers/cities/oslo", "city", "Relocating to Oslo", "both", "careers-alert"),
        ("careers/cities/toronto", "city", "Relocating to Toronto", "both", "careers-alert"),
        ("careers/cities/london", "city", "Relocating to London", "both", "careers-alert"),
        ("careers/cities/riyadh", "city", "Relocating to Riyadh", "both", "careers-alert"),
        ("press-desk", "press", "Press desk — quote UAO", "press", "press-quote"),
        ("advertise", "advertiser", "Advertise packages", "service-provider", "advertiser-call"),
    ]
    for slug, typ, title, audience, conv in wave1:
        rows.append(
            row(
                wave="1",
                type=typ,
                slug=slug,
                title=title,
                audience=audience,
                conversion=conv,
                priority="P0",
                status="drafted-in-repo",
                notes="Wave 1 publish pack",
            )
        )

    institutions = [
        ("norges-bank-investment-management-nbim", "Norges Bank Investment Management", "SWF/reserve", "live-check"),
        ("public-investment-fund-pif", "Public Investment Fund (Saudi Arabia)", "SWF", "live-check"),
        ("adia-abu-dhabi-investment-authority", "Abu Dhabi Investment Authority", "SWF", "live-check"),
        ("mubadala-investment-company", "Mubadala Investment Company", "SWF", "live-check"),
        ("adq-abu-dhabi", "ADQ", "SWF", "live-check"),
        ("qatar-investment-authority-qia", "Qatar Investment Authority", "SWF", "live-check"),
        ("kuwait-investment-authority-kia", "Kuwait Investment Authority", "SWF", "live-check"),
        ("gic-singapore-explained", "GIC", "SWF", "live-check"),
        ("temasek-holdings-explained", "Temasek", "SWF/strategic", "live-check"),
        ("china-investment-corporation-cic", "China Investment Corporation", "SWF", "needed"),
        ("safe-china-reserves", "SAFE (China)", "Reserve", "needed"),
        ("hkma-exchange-fund", "HKMA Exchange Fund", "Reserve", "needed"),
        ("korea-investment-corporation-kic", "Korea Investment Corporation", "SWF", "needed"),
        ("future-fund-australia-explained", "Future Fund", "SWF", "live-check"),
        ("nz-super-fund-explained", "NZ Super Fund", "SWF/pension-reserve", "needed"),
        ("cpp-investments-explained", "CPP Investments", "Public pension", "live-check"),
        ("ontario-teachers-pension-plan", "Ontario Teachers' Pension Plan", "Public pension", "needed"),
        ("cdpq-explained", "CDPQ", "Public pension", "needed"),
        ("psp-investments", "PSP Investments", "Public pension", "needed"),
        ("omers-explained", "OMERS", "Public pension", "needed"),
        ("aimco-explained", "AIMCo", "Public pension", "needed"),
        ("bcimc-bci", "BCI", "Public pension", "needed"),
        ("calpers-explained-largest-us-pension-fund", "CalPERS", "Public pension", "live-check"),
        ("calstrs-explained", "CalSTRS", "Public pension", "live-check"),
        ("wisconsin-investment-board-swib", "SWIB", "Public pension", "live-check"),
        ("gpif-japan-explained", "GPIF", "Public pension", "live-check"),
        ("abp-netherlands-pension-fund-explained", "ABP", "Public pension", "live-check"),
        ("pfzw-netherlands", "PFZW", "Public pension", "needed"),
        ("atp-denmark", "ATP", "Public pension", "needed"),
        ("alecta-sweden", "Alecta", "Public pension", "needed"),
        ("uss-universities-superannuation-scheme", "USS", "Public pension", "live-check"),
        ("uss-explained-merge", "USS canonical merge", "Public pension", "merge"),
        ("australian-super", "AustralianSuper", "Public pension", "needed"),
        ("aware-super", "Aware Super", "Public pension", "needed"),
        ("cbus-super", "Cbus", "Public pension", "needed"),
        ("nps-korea", "National Pension Service (Korea)", "Public pension", "needed"),
        ("epfo-india", "EPFO (India)", "Public pension", "needed"),
        ("employees-provident-fund-malaysia", "EPF Malaysia", "Public pension", "needed"),
        ("gepf-south-africa", "GEPF", "Public pension", "needed"),
        ("pic-south-africa", "Public Investment Corporation", "Public pension", "needed"),
        ("previ-brazil", "Previ", "Public pension", "needed"),
        ("afore-xxi-banorte", "Afore XXI Banorte", "Pension", "needed"),
        ("yale-investments-office", "Yale Investments Office", "Endowment", "needed"),
        ("harvard-management-company", "Harvard Management Company", "Endowment", "needed"),
        ("stanford-management-company", "Stanford Management Company", "Endowment", "needed"),
        ("princeton-investment-company", "PRINCO", "Endowment", "needed"),
        ("mit-investment-management-company", "MITIMCo", "Endowment", "needed"),
        ("university-of-texas-imf", "UTIMCO", "Endowment", "needed"),
        ("wellcome-trust", "Wellcome Trust", "Foundation", "needed"),
        ("gates-foundation-trust", "Gates Foundation Trust", "Foundation", "needed"),
        ("ford-foundation", "Ford Foundation", "Foundation", "needed"),
        ("khazanah-explained", "Khazanah", "SWF", "needed"),
        ("mumtalakat-bahrain", "Mumtalakat", "SWF", "needed"),
        ("qia-vs-adia", "QIA vs ADIA", "Comparison", "needed"),
        ("nbim-vs-gic", "NBIM vs GIC", "Comparison", "refresh-drafted"),
        ("cpp-vs-calpers", "CPP Investments vs CalPERS", "Comparison", "needed"),
        ("otpp-vs-cdpq", "OTPP vs CDPQ", "Comparison", "needed"),
        ("pif-vs-mubadala", "PIF vs Mubadala", "Comparison", "refresh-drafted"),
        ("mgx-abu-dhabi-ai-fund", "MGX", "SWF/vehicle", "live-check"),
        ("adnoc-investment", "ADNOC investment vehicles", "Strategic", "needed"),
        ("aramco-sovereign-adjacent", "Aramco as owner-adjacent capital", "Strategic", "needed"),
        ("norges-governance-ministry-finance", "NBIM and the Ministry of Finance", "Governance", "needed"),
        ("alaska-permanent-fund", "Alaska Permanent Fund", "SWF", "needed"),
        ("alberta-heritage-fund", "Alberta Heritage Savings Trust Fund", "SWF", "needed"),
        ("texas-permanent-school-fund", "Texas Permanent School Fund", "SWF-like", "needed"),
        ("new-mexico-state-investment-council", "NMSIC", "Public pension/SWF-like", "needed"),
        ("irish-strategic-investment-fund", "ISIF", "Strategic", "needed"),
        ("bpifrance", "Bpifrance", "Strategic", "needed"),
        ("kfw-capital", "KfW Capital", "Development", "needed"),
        ("cdc-group-bii", "British International Investment", "Development", "needed"),
        ("ifc-as-owner-adjacent", "IFC as owner-adjacent", "Development", "needed"),
        ("adib-vs-owner", "Do not confuse banks with owners — explainer", "Explainer", "needed"),
        ("new-york-state-common-retirement", "NYS Common Retirement Fund", "Public pension", "needed"),
        ("new-york-city-crs", "NYC Retirement Systems", "Public pension", "needed"),
        ("florida-sba", "Florida State Board of Administration", "Public pension", "needed"),
        ("texas-trs", "Teacher Retirement System of Texas", "Public pension", "needed"),
        ("calstrs-vs-calpers", "CalSTRS vs CalPERS", "Comparison", "needed"),
        ("ohio-opers", "OPERS", "Public pension", "needed"),
        ("ohio-str", "STRS Ohio", "Public pension", "needed"),
        ("michigan-sistf", "Michigan State Treasurer / SISTF", "Public pension", "needed"),
        ("pennsylvania-psers", "PSERS", "Public pension", "needed"),
        ("pennsylvania-sers", "SERS Pennsylvania", "Public pension", "needed"),
        ("new-jersey-division-of-investment", "NJ Division of Investment", "Public pension", "needed"),
        ("north-carolina-treasurer", "North Carolina Treasurer", "Public pension", "needed"),
        ("washington-state-investment-board", "WSIB", "Public pension", "needed"),
        ("oregon-pers-investments", "Oregon State Treasury / PERS", "Public pension", "needed"),
        ("massachusetts-prim", "PRIM", "Public pension", "needed"),
        ("virginia-retirement-system", "VRS", "Public pension", "needed"),
        ("georgia-trs", "TRS Georgia", "Public pension", "needed"),
        ("illinois-isbi", "ISBI", "Public pension", "needed"),
        ("illinois-trs", "TRS Illinois", "Public pension", "needed"),
        ("los-angeles-lacroa", "LACERA", "Public pension", "needed"),
        ("san-francisco-sfers", "SFERS", "Public pension", "needed"),
        ("teacher-retirement-system-of-texas-cio", "TRS Texas CIO office", "Public pension", "needed"),
        ("cpp-vs-otpp-vs-cdpq", "The Canadian large-plan triangle", "Comparison", "needed"),
        ("unjps-united-nations", "UNJSPF", "Pension", "needed"),
        ("cern-pension-fund", "CERN Pension Fund", "Pension", "needed"),
        ("european-investment-fund", "EIF as owner-adjacent", "Development", "needed"),
        ("european-investment-bank-treasury", "EIB treasury as owner-adjacent", "Development", "needed"),
        ("adnoc-xrg", "XRG / ADNOC international capital", "Strategic", "needed"),
        ("oman-investment-authority", "Oman Investment Authority", "SWF", "needed"),
        ("bahrain-mumtalakat-refresh", "Mumtalakat (full profile)", "SWF", "needed"),
        ("libya-lia", "Libyan Investment Authority", "SWF", "needed"),
        ("turkey-tvf", "Turkey Wealth Fund", "SWF", "needed"),
        ("russia-nwf-historical", "Russian NWF — historical/context only", "SWF", "needed"),
        ("kazakhstan-samruk-kazyna", "Samruk-Kazyna", "SWF", "needed"),
        ("azerbaijan-sofar", "SOFAZ", "SWF", "needed"),
        ("timor-leste-petroleum-fund", "Timor-Leste Petroleum Fund", "SWF", "refresh-drafted"),
        ("botswana-pula-fund", "Pula Fund", "SWF", "needed"),
        ("ghana-petroleum-funds", "Ghana Petroleum Funds", "SWF", "refresh-drafted"),
        ("nsia-nigeria", "Nigeria Sovereign Investment Authority", "SWF", "needed"),
        ("angola-fsdea", "FSDEA", "SWF", "needed"),
        ("egypt-tsfe", "Egypt TSFE", "SWF", "needed"),
        ("morocco-iqtisadi", "Moroccan strategic funds", "SWF", "needed"),
        ("indonesia-danantara-inia", "Indonesia sovereign/strategic vehicles", "SWF", "needed"),
        ("india-nco-ninf", "India NIIF", "Strategic", "needed"),
        ("philippines-maharlika", "Maharlika Investment Fund", "SWF", "needed"),
        ("vietnam-scic", "SCIC", "SWF", "needed"),
        ("thailand-gic-not", "GPF Thailand", "Public pension", "needed"),
        ("hong-kong-mpfa-system", "Hong Kong MPF system", "Pension", "needed"),
        ("singapore-cpf", "CPF vs GIC vs Temasek", "Comparison", "needed"),
        ("japan-gpif-vs-pension-funds", "GPIF vs smaller Japanese plans", "Comparison", "needed"),
        ("canada-pension-model-explained", "Canadian pension model (franchise)", "Explainer", "needed"),
        ("yale-endowment-model-merge", "Yale model — merge twins", "merge", "merge"),
        ("harvard-vs-yale-endowment", "Harvard vs Yale endowment", "Comparison", "needed"),
        ("princeton-vs-stanford-endowment", "Princeton vs Stanford", "Comparison", "needed"),
        ("notre-dame-endowment", "Notre Dame endowment", "Endowment", "needed"),
        ("duke-endowment-vs-duke-university", "Duke (disambiguation)", "Endowment", "needed"),
        ("columbia-investment-management", "Columbia IMC", "Endowment", "needed"),
        ("upenn-investment-office", "Penn investment office", "Endowment", "needed"),
        ("chicago-endowment", "University of Chicago endowment", "Endowment", "needed"),
        ("rice-endowment", "Rice University endowment", "Endowment", "needed"),
        ("unc-chapel-hill-endowment", "UNC Chapel Hill endowment", "Endowment", "needed"),
        ("georgia-tech-endowment", "Georgia Tech endowment", "Endowment", "needed"),
        ("boston-university-endowment", "Boston University endowment", "Endowment", "needed"),
        ("indiana-university-endowment", "Indiana University endowment", "Endowment", "needed"),
        ("boston-college-endowment", "Boston College endowment", "Endowment", "needed"),
        ("tulane-endowment", "Tulane University endowment", "Endowment", "needed"),
        ("wake-forest-endowment", "Wake Forest University endowment", "Endowment", "needed"),
        ("tufts-endowment", "Tufts University endowment", "Endowment", "needed"),
        ("case-western-reserve-endowment", "Case Western Reserve University endowment", "Endowment", "needed"),
        ("syracuse-endowment", "Syracuse University endowment", "Endowment", "needed"),
        ("baylor-endowment", "Baylor University endowment", "Endowment", "needed"),
        ("northeastern-endowment", "Northeastern University endowment", "Endowment", "needed"),
        ("george-washington-endowment", "George Washington University endowment", "Endowment", "needed"),
        ("university-of-miami-endowment", "University of Miami endowment", "Endowment", "needed"),
        ("university-of-pittsburgh-endowment", "University of Pittsburgh endowment", "Endowment", "needed"),
        ("tcu-endowment", "Texas Christian University endowment", "Endowment", "needed"),
        ("villanova-endowment", "Villanova University endowment", "Endowment", "needed"),
        ("lehigh-university-endowment", "Lehigh University endowment", "Endowment", "needed"),
        ("fordham-endowment", "Fordham University endowment", "Endowment", "needed"),
        ("purdue-endowment", "Purdue University endowment", "Endowment", "needed"),
        ("ohio-state-endowment", "Ohio State University endowment", "Endowment", "needed"),
        ("penn-state-endowment", "Penn State endowment", "Endowment", "needed"),
        ("university-of-richmond-endowment", "University of Richmond endowment", "Endowment", "needed"),
        ("drexel-endowment", "Drexel University endowment", "Endowment", "needed"),
        ("brandeis-endowment", "Brandeis University endowment", "Endowment", "needed"),
        ("pepperdine-endowment", "Pepperdine University endowment", "Endowment", "needed"),
        ("temple-endowment", "Temple University endowment", "Endowment", "needed"),
        ("howard-endowment", "Howard University endowment", "Endowment", "needed"),
        ("rutgers-endowment", "Rutgers endowment", "Endowment", "needed"),
        ("smith-college-endowment", "Smith College endowment", "Endowment", "needed"),
        ("university-of-delaware-endowment", "University of Delaware endowment", "Endowment", "needed"),
        ("bowdoin-endowment", "Bowdoin College endowment", "Endowment", "needed"),
        ("nc-state-endowment", "NC State endowment", "Endowment", "needed"),
        ("university-of-alabama-endowment", "University of Alabama endowment", "Endowment", "needed"),
        ("middlebury-endowment", "Middlebury College endowment", "Endowment", "needed"),
        ("bates-endowment", "Bates College endowment", "Endowment", "needed"),
        ("vassar-endowment", "Vassar College endowment", "Endowment", "needed"),
        ("bucknell-endowment", "Bucknell University endowment", "Endowment", "needed"),
        ("clemson-endowment", "Clemson University endowment", "Endowment", "needed"),
        ("wesleyan-endowment", "Wesleyan University endowment", "Endowment", "needed"),
        ("amherst-endowment", "Amherst College endowment", "Endowment", "needed"),
        ("wellesley-endowment", "Wellesley College endowment", "Endowment", "needed"),
        ("swarthmore-endowment", "Swarthmore College endowment", "Endowment", "needed"),
        ("grinnell-endowment", "Grinnell College endowment", "Endowment", "needed"),
        ("pomona-endowment", "Pomona College endowment", "Endowment", "needed"),
        ("colgate-endowment", "Colgate University endowment", "Endowment", "needed"),
        ("davidson-endowment", "Davidson College endowment", "Endowment", "needed"),
        ("holy-cross-endowment", "College of the Holy Cross endowment", "Endowment", "needed"),
        ("carleton-endowment", "Carleton College endowment", "Endowment", "needed"),
        ("haverford-endowment", "Haverford College endowment", "Endowment", "needed"),
        ("oberlin-endowment", "Oberlin College endowment", "Endowment", "needed"),
        ("kenyon-endowment", "Kenyon College endowment", "Endowment", "needed"),
        ("macalester-endowment", "Macalester College endowment", "Endowment", "needed"),
        ("lafayette-endowment", "Lafayette College endowment", "Endowment", "needed"),
        ("trinity-college-endowment", "Trinity College endowment", "Endowment", "needed"),
        ("barnard-endowment", "Barnard College endowment", "Endowment", "needed"),
        ("bryn-mawr-endowment", "Bryn Mawr College endowment", "Endowment", "needed"),
        ("mount-holyoke-endowment", "Mount Holyoke College endowment", "Endowment", "needed"),
        ("colorado-college-endowment", "Colorado College endowment", "Endowment", "needed"),
        ("occidental-endowment", "Occidental College endowment", "Endowment", "needed"),
        ("connecticut-college-endowment", "Connecticut College endowment", "Endowment", "needed"),
        ("dickinson-endowment", "Dickinson College endowment", "Endowment", "needed"),
        ("union-college-endowment", "Union College endowment", "Endowment", "needed"),
        ("reed-endowment", "Reed College endowment", "Endowment", "needed"),
        ("scripps-endowment", "Scripps College endowment", "Endowment", "needed"),
        ("st-olaf-endowment", "St. Olaf College endowment", "Endowment", "needed"),
        ("ursinus-endowment", "Ursinus College endowment", "Endowment", "needed"),
        ("whitman-endowment", "Whitman College endowment", "Endowment", "needed"),
        ("wabash-endowment", "Wabash College endowment", "Endowment", "needed"),
        ("furman-endowment", "Furman University endowment", "Endowment", "needed"),
        ("stetson-endowment", "Stetson University endowment", "Endowment", "needed"),
        ("lewis-clark-endowment", "Lewis & Clark College endowment", "Endowment", "needed"),
        ("hope-college-endowment", "Hope College endowment", "Endowment", "needed"),
        ("hamline-endowment", "Hamline University endowment", "Endowment", "needed"),
        ("puget-sound-endowment", "University of Puget Sound endowment", "Endowment", "needed"),
        ("elon-endowment", "Elon University endowment", "Endowment", "needed"),
        ("rit-endowment", "Rochester Institute of Technology endowment", "Endowment", "needed"),
        ("denison-university-endowment", "Denison University endowment", "Endowment", "needed"),
        ("bentley-endowment", "Bentley University endowment", "Endowment", "needed"),
        ("marist-endowment", "Marist University endowment", "Endowment", "needed"),
        ("southwestern-endowment", "Southwestern University endowment", "Endowment", "needed"),
        ("calvin-endowment", "Calvin University endowment", "Endowment", "needed"),
        ("stevens-endowment", "Stevens Institute of Technology endowment", "Endowment", "needed"),
        ("embry-riddle-endowment", "Embry-Riddle Aeronautical University endowment", "Endowment", "needed"),
        ("florida-tech-endowment", "Florida Institute of Technology endowment", "Endowment", "needed"),
        ("lawrence-university-endowment", "Lawrence University endowment", "Endowment", "needed"),
        ("barry-endowment", "Barry University endowment", "Endowment", "needed"),
        ("lynn-endowment", "Lynn University endowment", "Endowment", "needed"),
        ("nova-southeastern-endowment", "Nova Southeastern University endowment", "Endowment", "needed"),
        ("warner-university-endowment", "Warner University endowment", "Endowment", "needed"),
        ("ringling-endowment", "Ringling College of Art and Design endowment", "Endowment", "needed"),
        ("miami-dade-college-foundation", "Miami Dade College Foundation endowment", "Endowment", "needed"),
        ("west-florida-foundation-endowment", "University of West Florida Foundation endowment", "Endowment", "needed"),
        ("famu-foundation-endowment", "FAMU Foundation endowment", "Endowment", "needed"),
        ("florida-college-endowment", "Florida College endowment", "Endowment", "needed"),
        ("valencia-college-foundation", "Valencia College Foundation endowment", "Endowment", "needed"),
        ("state-college-florida-foundation", "State College of Florida Foundation endowment", "Endowment", "needed"),
        ("florida-southwestern-foundation", "Florida SouthWestern State College Foundation endowment", "Endowment", "needed"),
        ("eastern-florida-foundation", "Eastern Florida State College Foundation endowment", "Endowment", "needed"),
        ("hillsborough-community-college-foundation", "Hillsborough Community College Foundation endowment", "Endowment", "needed"),
        ("north-florida-college-foundation", "North Florida College Foundation endowment", "Endowment", "needed"),
        ("tallahassee-state-college-foundation", "Tallahassee State College Foundation endowment", "Endowment", "needed"),
        ("gulf-coast-state-college-foundation", "Gulf Coast State College Foundation endowment", "Endowment", "needed"),
        ("florida-keys-educational-foundation", "Florida Keys Educational Foundation endowment", "Endowment", "needed"),
        ("university-of-florida-foundation", "University of Florida Foundation endowment", "Endowment", "needed"),
        ("florida-international-university-foundation", "Florida International University Foundation endowment", "Endowment", "needed"),
        ("university-of-kentucky-endowment", "University of Kentucky endowment", "Endowment", "needed"),
        ("university-of-kentucky-alumni-endowment", "University of Kentucky Alumni Association endowment", "Endowment", "needed"),
        ("university-of-kentucky-research-foundation", "University of Kentucky Research Foundation endowment", "Endowment", "needed"),
        ("university-of-kentucky-humanities-endowment", "University of Kentucky Humanities Foundation endowment", "Endowment", "needed"),
        ("gluck-equine-endowment", "Gluck Equine Research Foundation endowment", "Endowment", "needed"),
        ("university-of-kentucky-mining-endowment", "University of Kentucky Mining Engineering Foundation endowment", "Endowment", "needed"),
        ("chipola-college-foundation", "Chipola College Foundation endowment", "Endowment", "needed"),
        ("harvey-mudd-endowment", "Harvey Mudd College endowment", "Endowment", "needed"),
        ("claremont-mckenna-endowment", "Claremont McKenna College endowment", "Endowment", "needed"),
        ("university-of-mississippi-foundation", "University of Mississippi Foundation endowment", "Endowment", "needed"),
        ("university-of-louisville-foundation", "University of Louisville Foundation endowment", "Endowment", "needed"),
        ("pinellas-county-education-foundation", "Pinellas County Education Foundation endowment", "Endowment", "needed"),
        ("university-of-arkansas-foundation", "University of Arkansas Foundation endowment", "Endowment", "needed"),
        ("mississippi-state-university-foundation", "Mississippi State University Foundation endowment", "Endowment", "needed"),
        ("montana-state-university-foundation", "Montana State University Foundation endowment", "Endowment", "needed"),
        ("missouri-state-university-foundation", "Missouri State University Foundation endowment", "Endowment", "needed"),
        ("hillsborough-education-foundation", "Hillsborough Education Foundation endowment", "Endowment", "needed"),
        ("university-of-illinois-foundation", "University of Illinois Foundation endowment", "Endowment", "needed"),
        ("university-of-minnesota-foundation", "University of Minnesota Foundation endowment", "Endowment", "needed"),
        ("georgia-southern-university-foundation", "Georgia Southern University Foundation endowment", "Endowment", "needed"),
        ("kansas-state-university-foundation", "Kansas State University Foundation endowment", "Endowment", "needed"),
        ("northern-kentucky-university-foundation", "Northern Kentucky University Foundation endowment", "Endowment", "needed"),
        ("kansas-university-endowment", "Kansas University Endowment Association endowment", "Endowment", "needed"),
        ("university-of-nebraska-foundation", "University of Nebraska Foundation endowment", "Endowment", "needed"),
        ("university-at-buffalo-foundation", "University at Buffalo Foundation endowment", "Endowment", "needed"),
        ("oklahoma-state-university-foundation", "Oklahoma State University Foundation endowment", "Endowment", "needed"),
        ("university-of-hawaii-foundation", "University of Hawaii Foundation endowment", "Endowment", "needed"),
        ("university-of-wisconsin-foundation", "University of Wisconsin Foundation endowment", "Endowment", "needed"),
        ("university-of-dayton-endowment", "University of Dayton endowment", "Endowment", "needed"),
        ("medical-college-of-virginia-foundation", "Medical College of Virginia Foundation endowment", "Endowment", "needed"),
        ("xavier-university-endowment", "Xavier University endowment", "Endowment", "needed"),
        ("george-mason-university-foundation", "George Mason University Foundation endowment", "Endowment", "needed"),
        ("washington-and-lee-endowment", "Washington and Lee University endowment", "Endowment", "needed"),
        ("spelman-endowment", "Spelman College endowment", "Endowment", "needed"),
        ("college-of-charleston-foundation", "College of Charleston Foundation endowment", "Endowment", "needed"),
        ("hamilton-endowment", "Hamilton College endowment", "Endowment", "needed"),
        ("santa-clara-endowment", "Santa Clara University endowment", "Endowment", "needed"),
        ("willamette-endowment", "Willamette University endowment", "Endowment", "needed"),
        ("creighton-endowment", "Creighton University endowment", "Endowment", "needed"),
        ("chapman-endowment", "Chapman University endowment", "Endowment", "needed"),
        ("knox-endowment", "Knox College endowment", "Endowment", "needed"),
        ("university-of-iowa-center-for-advancement", "University of Iowa Center for Advancement endowment", "Endowment", "needed"),
        ("university-of-portland-endowment", "University of Portland endowment", "Endowment", "needed"),
        ("seattle-university-endowment", "Seattle University endowment", "Endowment", "needed"),
        ("university-of-san-diego-endowment", "University of San Diego endowment", "Endowment", "needed"),
        ("loyola-university-chicago-endowment", "Loyola University Chicago endowment", "Endowment", "needed"),
        ("university-of-st-thomas-endowment", "University of St. Thomas endowment", "Endowment", "needed"),
        ("marquette-endowment", "Marquette University endowment", "Endowment", "needed"),
        ("university-of-san-francisco-endowment", "University of San Francisco endowment", "Endowment", "needed"),
        ("saint-louis-university-endowment", "Saint Louis University endowment", "Endowment", "needed"),
        ("loyola-maryland-endowment", "Loyola University Maryland endowment", "Endowment", "needed"),
        ("duquesne-endowment", "Duquesne University endowment", "Endowment", "needed"),
        ("university-of-denver-endowment", "University of Denver endowment", "Endowment", "needed"),
        ("american-university-endowment", "American University endowment", "Endowment", "needed"),
        ("catholic-university-endowment", "Catholic University of America endowment", "Endowment", "needed"),
        ("detroit-mercy-endowment", "University of Detroit Mercy endowment", "Endowment", "needed"),
        ("pacific-lutheran-endowment", "Pacific Lutheran University endowment", "Endowment", "needed"),
        ("university-of-the-pacific-endowment", "University of the Pacific endowment", "Endowment", "needed"),
        ("university-of-toledo-foundation", "University of Toledo Foundation endowment", "Endowment", "needed"),
        ("college-of-saint-benedict-endowment", "College of Saint Benedict endowment", "Endowment", "needed"),
        ("siu-foundation", "SIU Foundation endowment", "Endowment", "needed"),
        ("kennesaw-state-university-foundation", "Kennesaw State University Foundation endowment", "Endowment", "needed"),
        ("university-of-alaska-foundation", "University of Alaska Foundation endowment", "Endowment", "needed"),
        ("csu-chico-foundation", "CSU Chico Foundation endowment", "Endowment", "needed"),
        ("towson-university-foundation", "Towson University Foundation endowment", "Endowment", "needed"),
        ("eastern-washington-university-foundation", "Eastern Washington University Foundation endowment", "Endowment", "needed"),
        ("western-oregon-university-foundation", "Western Oregon University Foundation endowment", "Endowment", "needed"),
        ("oregon-state-university-foundation", "Oregon State University Foundation endowment", "Endowment", "needed"),
        ("university-of-wyoming-foundation", "University of Wyoming Foundation endowment", "Endowment", "needed"),
        ("sfsu-foundation", "San Francisco State University Foundation endowment", "Endowment", "needed"),
        ("campanile-foundation", "The Campanile Foundation endowment", "Endowment", "needed"),
        ("university-of-oregon-foundation", "University of Oregon Foundation endowment", "Endowment", "needed"),
        ("university-of-idaho-foundation", "University of Idaho Foundation endowment", "Endowment", "needed"),
        ("idaho-state-university-foundation", "Idaho State University Foundation endowment", "Endowment", "needed"),
        ("texas-state-university-foundation", "Texas State University Development Foundation endowment", "Endowment", "needed"),
        ("colorado-state-university-foundation", "Colorado State University Foundation endowment", "Endowment", "needed"),
        ("university-of-colorado-foundation", "University of Colorado Foundation endowment", "Endowment", "needed"),
        ("college-of-western-idaho-foundation", "College of Western Idaho Foundation endowment", "Endowment", "needed"),
        ("cal-state-fullerton-philanthropic-foundation", "Cal State Fullerton Philanthropic Foundation endowment", "Endowment", "needed"),
        ("university-of-montana-foundation", "University of Montana Foundation endowment", "Endowment", "needed"),
        ("csusb-philanthropic-foundation", "CSUSB Philanthropic Foundation endowment", "Endowment", "needed"),
        ("csu-san-marcos-foundation", "CSU San Marcos Foundation endowment", "Endowment", "needed"),
        ("northeastern-illinois-university-foundation", "Northeastern Illinois University Foundation endowment", "Endowment", "needed"),
        ("illinois-state-university-foundation", "Illinois State University Foundation endowment", "Endowment", "needed"),
        ("eastern-illinois-university-foundation", "Eastern Illinois University Foundation endowment", "Endowment", "needed"),
        ("northern-illinois-university-foundation", "Northern Illinois University Foundation endowment", "Endowment", "needed"),
        ("siue-foundation", "SIUE Foundation endowment", "Endowment", "needed"),
        ("university-of-central-missouri-foundation", "University of Central Missouri Foundation endowment", "Endowment", "needed"),
        ("southeast-missouri-university-foundation", "Southeast Missouri University Foundation endowment", "Endowment", "needed"),
        ("washburn-university-foundation", "Washburn University Foundation endowment", "Endowment", "needed"),
        ("missouri-western-state-university-foundation", "Missouri Western State University Foundation endowment", "Endowment", "needed"),
        ("emporia-state-university-foundation", "Emporia State University Foundation endowment", "Endowment", "needed"),
        ("wichita-state-university-foundation", "Wichita State University Foundation endowment", "Endowment", "needed"),
        ("beloit-endowment", "Beloit College endowment", "Endowment", "needed"),
        ("carthage-endowment", "Carthage College endowment", "Endowment", "needed"),
        ("edgewood-college-endowment", "Edgewood College endowment", "Endowment", "needed"),
        ("luther-college-endowment", "Luther College endowment", "Endowment", "needed"),
        ("grand-view-university-endowment", "Grand View University endowment", "Endowment", "needed"),
        ("concordia-university-st-paul-endowment", "Concordia University St. Paul endowment", "Endowment", "needed"),
        ("ohio-wesleyan-endowment", "Ohio Wesleyan University endowment", "Endowment", "needed"),
        ("hampshire-college-endowment", "Hampshire College endowment", "Endowment", "needed"),
        ("washington-college-endowment", "Washington College endowment", "Endowment", "needed"),
        ("wayne-state-foundation-nebraska", "Wayne State Foundation Nebraska endowment", "Endowment", "needed"),
        ("washington-state-university-foundation", "Washington State University Foundation endowment", "Endowment", "needed"),
        ("lake-forest-college-endowment", "Lake Forest College endowment", "Endowment", "needed"),
        ("northwest-university-endowment", "Northwest University endowment", "Endowment", "needed"),
        ("whittier-college-endowment", "Whittier College endowment", "Endowment", "needed"),
        ("central-washington-university-foundation", "Central Washington University Foundation endowment", "Endowment", "needed"),
        ("wright-state-university-foundation", "Wright State University Foundation endowment", "Endowment", "needed"),
        ("northern-michigan-university-foundation", "Northern Michigan University Foundation endowment", "Endowment", "needed"),
        ("lake-superior-state-university-foundation", "Lake Superior State University Foundation endowment", "Endowment", "needed"),
        ("ferris-foundation", "Ferris Foundation endowment", "Endowment", "needed"),
        ("whitworth-university-endowment", "Whitworth University endowment", "Endowment", "needed"),
        ("baldwin-wallace-university-endowment", "Baldwin Wallace University endowment", "Endowment", "needed"),
        ("linfield-university-endowment", "Linfield University endowment", "Endowment", "needed"),
        ("heidelberg-university-endowment", "Heidelberg University endowment", "Endowment", "needed"),
        ("goucher-college-endowment", "Goucher College endowment", "Endowment", "needed"),
        ("capital-university-endowment", "Capital University endowment", "Endowment", "needed"),
        ("regis-college-endowment", "Regis College endowment", "Endowment", "needed"),
        ("mississippi-university-for-women-foundation", "Mississippi University for Women Foundation endowment", "Endowment", "needed"),
        ("endicott-college-endowment", "Endicott College endowment", "Endowment", "needed"),
        ("lasell-university-endowment", "Lasell University endowment", "Endowment", "needed"),
        ("curry-college-endowment", "Curry College endowment", "Endowment", "needed"),
        ("assumption-university-endowment", "Assumption University endowment", "Endowment", "needed"),
        ("stonehill-college-endowment", "Stonehill College endowment", "Endowment", "needed"),
        ("springfield-college-endowment", "Springfield College endowment", "Endowment", "needed"),
        ("clark-university-endowment", "Clark University endowment", "Endowment", "needed"),
        ("wentworth-institute-endowment", "Wentworth Institute of Technology endowment", "Endowment", "needed"),
        ("lesley-university-endowment", "Lesley University endowment", "Endowment", "needed"),
        ("mcla-foundation", "Massachusetts College of Liberal Arts Foundation endowment", "Endowment", "needed"),
        ("nichols-college-endowment", "Nichols College endowment", "Endowment", "needed"),
        ("gordon-college-endowment", "Gordon College endowment", "Endowment", "needed"),
        ("anna-maria-college-endowment", "Anna Maria College endowment", "Endowment", "needed"),
        ("dean-college-endowment", "Dean College endowment", "Endowment", "needed"),
        ("suffolk-university-endowment", "Suffolk University endowment", "Endowment", "needed"),
        ("wheaton-college-massachusetts-endowment", "Wheaton College Massachusetts endowment", "Endowment", "needed"),
        ("olin-college-endowment", "Olin College endowment", "Endowment", "needed"),
        ("american-international-college-endowment", "American International College endowment", "Endowment", "needed"),
        ("babson-college-endowment", "Babson College endowment", "Endowment", "needed"),
        ("emerson-college-endowment", "Emerson College endowment", "Endowment", "needed"),
        ("mcphs-endowment", "MCPHS endowment", "Endowment", "needed"),
        ("hellenic-college-endowment", "Hellenic College endowment", "Endowment", "needed"),
        ("boston-architectural-college-endowment", "Boston Architectural College endowment", "Endowment", "needed"),
        ("berklee-college-endowment", "Berklee College of Music endowment", "Endowment", "needed"),
        ("johnson-wales-endowment", "Johnson & Wales University endowment", "Endowment", "needed"),
        ("university-of-rhode-island-foundation", "University of Rhode Island Foundation endowment", "Endowment", "needed"),
        ("university-of-connecticut-foundation", "University of Connecticut Foundation endowment", "Endowment", "needed"),
        ("risd-endowment", "Rhode Island School of Design endowment", "Endowment", "needed"),
        ("scsu-foundation", "Southern Connecticut State University Foundation endowment", "Endowment", "needed"),
        ("wcsu-foundation", "Western Connecticut State University Foundation endowment", "Endowment", "needed"),
        ("unity-environmental-endowment", "Unity Environmental University endowment", "Endowment", "needed"),
        ("new-england-college-of-optometry-endowment", "New England College of Optometry endowment", "Endowment", "needed"),
        ("california-lutheran-endowment", "California Lutheran University endowment", "Endowment", "needed"),
        ("portland-state-university-foundation", "Portland State University Foundation endowment", "Endowment", "needed"),
        ("southern-oregon-university-foundation", "Southern Oregon University Foundation endowment", "Endowment", "needed"),
        ("worcester-polytechnic-endowment", "Worcester Polytechnic Institute endowment", "Endowment", "needed"),
        ("montana-technological-university-foundation", "Montana Technological University Foundation endowment", "Endowment", "needed"),
        ("minnesota-state-mankato-foundation", "Minnesota State University Mankato Foundation endowment", "Endowment", "needed"),
        ("boise-state-university-foundation", "Boise State University Foundation endowment", "Endowment", "needed"),
        ("metropolitan-state-denver-foundation", "Metropolitan State University of Denver Foundation endowment", "Endowment", "needed"),
        ("western-colorado-university-foundation", "Western Colorado University Foundation endowment", "Endowment", "needed"),
        ("fort-lewis-college-foundation", "Fort Lewis College Foundation endowment", "Endowment", "needed"),
        ("unc-greensboro-endowment", "UNC Greensboro Endowment Fund", "Endowment", "needed"),
        ("merrimack-college-endowment", "Merrimack College endowment", "Endowment", "needed"),
        ("emmanuel-college-endowment", "Emmanuel College endowment", "Endowment", "needed"),
        ("emory-endowment", "Emory University endowment", "Endowment", "needed"),
        ("carnegie-mellon-endowment", "Carnegie Mellon University endowment", "Endowment", "needed"),
        ("caltech-endowment", "Caltech endowment", "Endowment", "needed"),
        ("university-of-virginia-endowment", "University of Virginia endowment", "Endowment", "needed"),
        ("mcgill-endowment", "McGill University endowment", "Endowment", "needed"),
        ("cornell-endowment", "Cornell University endowment", "Endowment", "needed"),
        ("vanderbilt-endowment", "Vanderbilt University endowment", "Endowment", "needed"),
        ("brown-endowment", "Brown University endowment", "Endowment", "needed"),
        ("dartmouth-endowment", "Dartmouth College endowment", "Endowment", "needed"),
        ("washington-university-endowment", "Washington University in St. Louis endowment", "Endowment", "needed"),
        ("northwestern-endowment", "Northwestern endowment", "Endowment", "needed"),
        ("johns-hopkins-endowment", "Johns Hopkins endowment", "Endowment", "needed"),
        ("nyu-endowment", "NYU endowment", "Endowment", "needed"),
        ("usc-endowment", "USC endowment", "Endowment", "needed"),
        ("university-of-california-regents", "UC Investments", "Endowment/public", "needed"),
        ("university-of-michigan-endowment", "University of Michigan", "Endowment", "needed"),
        ("utimco-vs-texas-trs", "UTIMCO vs TRS Texas", "Comparison", "needed"),
        ("canadian-university-endowments-hub", "Canadian university endowments", "Endowment", "needed"),
        ("oxford-endowment-ousl", "Oxford endowments", "Endowment", "needed"),
        ("cambridge-endowment", "Cambridge endowments", "Endowment", "needed"),
        ("eth-zurich-foundation", "ETH Foundation", "Endowment", "needed"),
        ("kaust-endowment", "KAUST endowment", "Endowment", "needed"),
        ("nus-endowment", "NUS endowment", "Endowment", "needed"),
        ("allianz-investment-management", "Allianz investment book", "Insurer", "needed"),
        ("axa-investment-managers-owner-side", "AXA as owner", "Insurer", "needed"),
        ("prudential-pgim-owner-side", "Prudential as owner", "Insurer", "needed"),
        ("metlife-investment-management-owner", "MetLife as owner", "Insurer", "needed"),
        ("nippon-life", "Nippon Life", "Insurer", "needed"),
        ("dai-ichi-life", "Dai-ichi Life", "Insurer", "needed"),
        ("manulife-as-owner", "Manulife as owner", "Insurer", "needed"),
        ("sun-life-as-owner", "Sun Life as owner", "Insurer", "needed"),
        ("legal-and-general-as-owner", "Legal & General as owner", "Insurer", "needed"),
        ("aviva-as-owner", "Aviva as owner", "Insurer", "needed"),
        ("swiss-re-investment", "Swiss Re investment office", "Insurer", "needed"),
        ("munich-re-investment", "Munich Re investment office", "Insurer", "needed"),
        ("aia-as-owner", "AIA as owner", "Insurer", "needed"),
        ("ping-an-as-owner", "Ping An as owner", "Insurer", "needed"),
    ]
    for slug, title, notes, status in institutions:
        rows.append(
            row(
                wave="2",
                type="institution",
                slug=slug,
                title=title,
                audience="allocator",
                conversion="brief",
                priority="P0" if status == "needed" else "P1",
                status=status,
                notes=notes,
            )
        )

    people = [
        ("yasir-al-rumayyan-pif-governor", "Yasir Al-Rumayyan", "live-check"),
        ("nicolai-tangen-nbim", "Nicolai Tangen", "needed"),
        ("john-graham-cpp-investments-ceo", "John Graham", "live-check"),
        ("marcie-frost-calpers-ceo", "Marcie Frost", "live-check"),
        ("jo-taylor-otpp", "Jo Taylor", "needed"),
        ("deborah-orida-psp", "Deborah Orida", "needed"),
        ("charles-emond-cdpq", "Charles Emond", "needed"),
        ("lim-chow-kiat-gic", "Lim Chow Kiat", "needed"),
        ("dilhan-pillay-temasek", "Dilhan Pillay Sandrasegara", "needed"),
        ("yasmin-al-ali-placeholder", "REMOVE if unsourced — example only", "skip"),
        ("mark-machin-alumni-map", "Canadian pension alumni graph (hub)", "needed"),
        ("calpers-cio-current", "CalPERS CIO (current seat — verify name at publish)", "needed"),
        ("calstrs-cio-current", "CalSTRS CIO (verify at publish)", "needed"),
        ("gpif-cio-current", "GPIF CIO (verify at publish)", "needed"),
        ("abp-cio-current", "ABP CIO (verify at publish)", "needed"),
        ("future-fund-cio", "Future Fund CIO (verify at publish)", "needed"),
        ("harvard-cio-current", "Harvard Management Company CEO/CIO", "needed"),
        ("yale-cio-current", "Yale CIO", "needed"),
        ("wellcome-cio-current", "Wellcome Trust CIO", "needed"),
        ("adia-managing-director", "ADIA MD (verify at publish)", "needed"),
        ("mubadala-ceo", "Mubadala CEO (verify at publish)", "needed"),
        ("qia-ceo", "QIA CEO (verify at publish)", "needed"),
        ("kia-md", "KIA managing director (verify at publish)", "needed"),
        ("cic-chairman", "CIC leadership (verify at publish)", "needed"),
        ("nps-korea-cio", "NPS Korea CIO (verify at publish)", "needed"),
        ("australiansuper-cio", "AustralianSuper CIO", "needed"),
        ("uss-cio", "USS CIO", "needed"),
        ("swib-cio", "SWIB CIO", "needed"),
        ("aimco-ceo", "AIMCo CEO", "needed"),
        ("omers-cio", "OMERS CIO", "needed"),
    ]
    for slug, title, status in people:
        if status == "skip":
            continue
        rows.append(
            row(
                wave="2",
                type="person",
                slug=f"people/allocator-class/{slug}",
                title=title,
                audience="allocator",
                conversion="brief",
                priority="P0",
                status=status,
                notes="Verify current title from official source on the day of publish",
            )
        )

    cities = [
        ("new-york", "New York"),
        ("boston", "Boston"),
        ("san-francisco", "San Francisco"),
        ("sacramento", "Sacramento"),
        ("montreal", "Montréal"),
        ("calgary", "Calgary"),
        ("vancouver", "Vancouver"),
        ("dubai", "Dubai"),
        ("doha", "Doha"),
        ("kuwait-city", "Kuwait City"),
        ("hong-kong", "Hong Kong"),
        ("tokyo", "Tokyo"),
        ("seoul", "Seoul"),
        ("sydney", "Sydney"),
        ("melbourne", "Melbourne"),
        ("wellington", "Wellington"),
        ("amsterdam", "Amsterdam"),
        ("the-hague", "The Hague"),
        ("stockholm", "Stockholm"),
        ("copenhagen", "Copenhagen"),
        ("zurich", "Zurich"),
        ("geneva", "Geneva"),
        ("frankfurt", "Frankfurt"),
        ("paris", "Paris"),
        ("dublin", "Dublin"),
        ("luxembourg", "Luxembourg"),
        ("milan", "Milan"),
        ("madrid", "Madrid"),
        ("johannesburg", "Johannesburg"),
        ("cape-town", "Cape Town"),
        ("nairobi", "Nairobi"),
        ("lagos", "Lagos"),
        ("sao-paulo", "São Paulo"),
        ("mexico-city", "Mexico City"),
        ("santiago", "Santiago"),
        ("beijing", "Beijing"),
        ("shanghai", "Shanghai"),
        ("mumbai", "Mumbai"),
        ("kuala-lumpur", "Kuala Lumpur"),
        ("jakarta", "Jakarta"),
        ("manila", "Manila"),
        ("taipei", "Taipei"),
        ("tel-aviv", "Tel Aviv"),
        ("istanbul", "Istanbul"),
        ("vienna", "Vienna"),
        ("brussels", "Brussels"),
        ("warsaw", "Warsaw"),
        ("helsinki", "Helsinki"),
        ("reykjavik", "Reykjavik"),
        ("perth", "Perth"),
    ]
    for slug, name in cities:
        rows.append(
            row(
                wave="2" if slug in {"new-york", "dubai", "hong-kong", "sydney", "amsterdam", "zurich"} else "3",
                type="city",
                slug=f"careers/cities/{slug}",
                title=f"Relocating to {name} for an asset-owner role",
                audience="both",
                conversion="careers-alert",
                priority="P1",
                status="needed",
                notes="Public rules only; no immigration advice",
            )
        )

    qa = [
        ("how-do-family-offices-hire-cios", "How do family offices hire CIOs?"),
        ("how-do-sovereign-wealth-funds-hire-lawyers", "How do sovereign wealth funds hire lawyers?"),
        ("what-is-a-family-office-technology-stack", "What is a family-office technology stack?"),
        ("what-does-an-investment-bank-do-for-a-pension-fund", "What does an investment bank do for a pension fund?"),
        ("how-do-endowments-pay-cios", "How are endowment CIOs paid? (sourced ranges only)"),
        ("what-is-a-strategic-council-membership-for-asset-owners", "What is a strategic research membership?"),
        ("how-to-get-quoted-as-an-asset-owner-publication", "How newsrooms quote allocator publications"),
        ("what-is-the-canadian-pension-model", "What is the Canadian pension model?"),
        ("what-is-a-development-finance-institution", "What is a DFI vs a SWF?"),
        ("how-do-insurers-invest-differently-from-pensions", "How do insurers invest differently from pensions?"),
        ("what-is-an-investment-committee", "What is an investment committee?"),
        ("what-is-a-reference-portfolio-merge", "Merge reference-portfolio twins"),
        ("what-is-a-total-portfolio-approach-merge", "Merge TPA twins"),
        ("santiago-principles-merge", "Merge Santiago twins"),
        ("how-do-pensions-use-ocios", "How do pensions use OCIOs?"),
        ("when-should-a-family-office-use-an-ocio", "When should a family office use an OCIO?"),
        ("what-is-a-fund-of-one", "What is a fund-of-one?"),
        ("what-is-an-sma-for-a-family-office", "What is an SMA for a family office?"),
        ("how-do-swfs-think-about-sanctions", "How do SWFs think about sanctions?"),
        ("what-is-look-through-risk", "What is look-through risk?"),
        ("what-is-a-co-invest-committee", "What is a co-invest committee?"),
        ("how-do-public-pensions-publish-holdings", "How do public pensions publish holdings?"),
        ("what-is-form-pf-vs-n-px", "Form PF vs N-PX for owners"),
        ("how-do-gulf-funds-work-with-placement-agents", "Gulf funds and placement agents"),
        ("what-is-a-family-constitution", "What is a family constitution?"),
        ("what-is-next-gen-governance", "What is next-gen governance in a family office?"),
        ("how-do-endowments-set-spending-rules", "How do endowments set spending rules?"),
        ("what-is-a-smoothing-rule", "What is a spending smoothing rule?"),
        ("how-do-corporate-pensions-run-de-risking", "How do corporate pensions de-risk?"),
        ("what-is-a-journey-plan", "What is a UK journey plan?"),
        ("how-do-australian-supers-differ-from-us-public-plans", "Australian super vs US public plans"),
        ("what-is-a-superannuation-trustee", "What is a superannuation trustee?"),
        ("how-do-latam-pension-afps-invest", "How do Latin American AFPs invest?"),
        ("what-is-an-afore", "What is an Afore?"),
        ("how-do-african-sovereign-funds-differ", "How do African sovereign funds differ?"),
        ("what-is-the-nigeria-sovereign-investment-authority", "NSIA explained"),
        ("what-is-the-angola-fsdea", "FSDEA explained"),
        ("what-is-pula-fund", "Pula Fund explained"),
        ("how-do-central-bank-reserves-differ-from-swfs", "Reserves vs SWFs (defend existing)"),
        ("what-is-a-stabilization-fund", "What is a stabilization fund?"),
        ("how-do-owners-use-secondaries", "How do owners use secondaries?"),
        ("what-is-a-gp-led-secondary-for-an-lp", "GP-led secondaries for LPs"),
        ("how-do-owners-think-about-tokenized-funds", "Tokenized funds for owners"),
        ("what-is-operational-due-diligence-for-an-lp", "ODD for asset owners"),
        ("how-do-owners-run-manager-selection", "How owners run manager selection"),
        ("what-is-a-consultant-database", "What is a consultant database?"),
        ("how-do-search-firms-work-for-cio-mandates", "How search firms run CIO mandates"),
        ("what-is-a-retained-search", "What is a retained search?"),
        ("how-do-compensation-consultants-price-cio-roles", "CIO compensation consultants"),
        ("what-is-carried-interest-inside-an-asset-owner", "Carry inside an asset owner"),
        ("how-do-owners-handle-personal-trading", "Personal trading policies"),
        ("what-is-a-code-of-ethics-for-an-investment-office", "Investment-office code of ethics"),
        ("how-do-owners-disclose-climate-votes", "Climate vote disclosure"),
        ("what-is-a-stewardship-code", "What is a stewardship code?"),
        ("how-do-japanese-pensions-steward", "Stewardship in Japanese pensions"),
        ("what-is-the-uk-stewardship-code", "UK Stewardship Code for owners"),
        ("how-do-family-offices-think-about-philanthropy-vs-the-book", "Philanthropy vs the investment book"),
        ("what-is-impact-alongside-a-universal-owner-book", "Impact vs universal ownership"),
        ("how-do-owners-underwrite-data-centers", "Underwriting data centers"),
        ("how-do-owners-underwrite-ports", "Underwriting ports"),
        ("how-do-owners-underwrite-grids", "Underwriting grids"),
        ("what-is-a-chokepoint-for-a-universal-owner", "What is a chokepoint?"),
        ("how-does-insurance-close-a-strait", "Insurance as a chokepoint (refresh Hormuz research)"),
        ("what-is-the-capital-stage-ledger", "Capital Stage Ledger (refresh)"),
        ("how-to-read-a-probability-desk-scenario", "How to read a Probability Desk scenario"),
        ("what-is-a-tripwire-in-scenario-analysis", "What is a tripwire?"),
        ("how-do-boards-use-scenario-weights", "How boards use scenario weights"),
        ("what-publications-do-cios-read", "What publications do CIOs read?"),
        ("who-covers-sovereign-wealth-funds", "Who covers sovereign wealth funds?"),
        ("ipe-vs-pensions-and-investments-vs-uao", "IPE vs P&I vs UAO (honest comparison)"),
        ("what-is-swfi-vs-a-newsroom", "SWFI vs a newsroom"),
        ("how-do-service-providers-advertise-to-asset-owners", "How service providers advertise to owners"),
        ("what-does-a-20k-a-month-media-buy-get-you", "What a $20k/month institutional media buy is"),
        ("how-do-recruiters-reach-sovereign-fund-talent", "How recruiters reach SWF talent"),
        ("what-is-an-institutional-talent-desk", "What is an Institutional Talent Desk?"),
        ("how-do-people-moves-signal-allocation-changes", "People moves as allocation signals"),
        ("what-is-in-housing-of-private-markets", "In-housing private markets"),
        ("how-do-owners-open-a-london-office", "How owners open a London office"),
        ("how-do-owners-open-a-new-york-office", "How owners open a New York office"),
        ("how-do-owners-open-a-singapore-office", "How owners open a Singapore office"),
        ("what-is-a-representative-office-vs-a-desk", "Rep office vs desk"),
        ("how-do-sanctions-change-a-family-office-bank", "Sanctions and family-office banking"),
        ("what-is-a-multi-custodian-model", "Multi-custodian model"),
        ("how-do-owners-pick-a-custodian", "How owners pick a custodian"),
        ("what-is-an-administrator-for-a-pension-plan", "Pension administrators"),
        ("how-do-cyber-insurers-underwrite-family-offices", "Cyber insurance for family offices"),
        ("what-is-principal-protection-for-a-family", "Principal protection (non-advice)"),
        ("how-do-next-gen-members-join-an-ic", "Next-gen on the investment committee"),
        ("what-is-a-family-investment-committee", "Family investment committee"),
        ("how-do-single-family-offices-unbundle", "How SFOs unbundle"),
        ("what-is-a-multi-family-office-fee", "MFO fees (sourced only)"),
        ("how-do-pensions-use-placement-agents", "Pensions and placement agents"),
        ("what-is-a-capital-introduction", "What is cap intro for an owner?"),
        ("how-do-owners-think-about-ipo-allocations", "IPO allocations for owners"),
        ("what-is-a-sovereign-co-invest-in-infrastructure", "Sovereign co-invests in infrastructure"),
        ("how-do-gulf-funds-invest-in-sports", "Gulf funds and sports assets"),
        ("how-do-gulf-funds-invest-in-ai", "Gulf funds and AI"),
        ("what-is-patriotic-capital", "What is patriotic capital?"),
        ("how-do-owners-treat-defense-as-an-asset-class", "Defense as an asset class"),
        ("what-is-a-national-security-screen-on-a-deal", "National security screens"),
        ("how-do-cfius-and-peers-affect-swfs", "CFIUS and SWFs"),
        ("what-is-golden-share", "What is a golden share?"),
        ("how-do-owners-map-supply-chains", "Supply-chain mapping for owners"),
        ("what-is-a-universal-owner-externality", "Universal-owner externalities"),
        ("how-to-use-uao-registry", "How to use the UAO Registry"),
        ("what-is-the-uao-100", "What is the UAO 100?"),
        ("how-we-audit-readership", "How UAO audits readership (public version)"),
    ]
    for slug, title in qa:
        wave = "1" if "merge" in slug else "2"
        rows.append(
            row(
                wave=wave,
                type="explainer",
                slug=slug,
                title=title,
                audience="both" if any(x in slug for x in ("advertise", "recruit", "20k", "directory")) else "allocator",
                conversion="brief",
                priority="P1",
                status="merge" if "merge" in slug else "needed",
                notes="",
            )
        )

    countries = [
        "norway",
        "saudi-arabia",
        "united-arab-emirates",
        "qatar",
        "kuwait",
        "singapore",
        "china",
        "hong-kong",
        "japan",
        "south-korea",
        "australia",
        "new-zealand",
        "canada",
        "united-states",
        "united-kingdom",
        "netherlands",
        "denmark",
        "sweden",
        "switzerland",
        "germany",
        "france",
        "ireland",
        "italy",
        "spain",
        "india",
        "malaysia",
        "indonesia",
        "brazil",
        "mexico",
        "chile",
        "south-africa",
        "nigeria",
        "kenya",
        "egypt",
        "turkey",
        "israel",
        "poland",
        "finland",
        "luxembourg",
        "belgium",
    ]
    owner_types = [
        "sovereign-wealth-funds",
        "public-pensions",
        "family-offices",
        "endowments",
        "insurers",
    ]
    for country in countries:
        for ot in owner_types:
            rows.append(
                row(
                    wave="3",
                    type="geo-hub",
                    slug=f"geo/{country}/{ot}",
                    title=f"{ot.replace('-', ' ').title()} in {country.replace('-', ' ').title()}",
                    audience="allocator",
                    conversion="brief",
                    priority="P2",
                    status="needed",
                    notes="Ship only when ≥5 child pages exist",
                )
            )

    themes = [
        "private-credit",
        "infrastructure",
        "ai-infrastructure",
        "energy-transition",
        "stewardship",
        "demographics",
        "geopolitics",
        "secondaries",
    ]
    for theme in themes:
        for ot in owner_types:
            rows.append(
                row(
                    wave="3",
                    type="theme",
                    slug=f"themes/{theme}/{ot}",
                    title=f"{theme.replace('-', ' ').title()} for {ot.replace('-', ' ')}",
                    audience="allocator",
                    conversion="brief",
                    priority="P2",
                    status="needed",
                    notes="Requires a UAO judgment, not a Wikipedia rewrite",
                )
            )

    directory_cats = [
        "consulting-ocio",
        "executive-search",
        "custody-administration",
        "data-and-index",
        "cybersecurity",
        "placement-agents",
    ]
    for cat in directory_cats:
        rows.append(
            row(
                wave="2",
                type="directory",
                slug=f"directory/{cat}",
                title=cat.replace("-", " ").title(),
                audience="both",
                conversion="advertiser-call",
                priority="P1",
                status="needed",
                notes="Hub first; firms only with three sourced facts",
            )
        )

    careers_intel = [
        ("cio-compensation-public-plans", "CIO compensation in public plans (sourced)"),
        ("first-year-inside-a-family-office", "First year inside a family office"),
        ("leaving-a-sovereign-fund", "Leaving a sovereign fund"),
        ("dual-career-moves-gulf", "Dual-career moves to the Gulf"),
        ("boarding-an-investment-committee", "Joining an investment committee"),
        ("internal-vs-external-cio-office", "Building vs renting a CIO office"),
        ("why-london-satellites-fail", "Why London satellites fail"),
        ("onboarding-a-deputy-cio", "Onboarding a deputy CIO"),
        ("succession-inside-a-public-plan", "Succession inside a public plan"),
        ("search-brief-for-a-real-assets-head", "Writing a real-assets head search brief"),
    ]
    for slug, title in careers_intel:
        rows.append(
            row(
                wave="2",
                type="careers",
                slug=f"careers/intelligence/{slug}",
                title=title,
                audience="both",
                conversion="careers-alert",
                priority="P1",
                status="needed",
                notes="",
            )
        )

    # Deduplicate by slug, first wins
    seen: set[str] = set()
    unique: list[dict] = []
    for r in rows:
        if r["slug"] in seen:
            continue
        seen.add(r["slug"])
        unique.append(r)

    OUT.write_text("")  # ensure path
    with OUT.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(unique)

    print(f"Wrote {len(unique)} slugs to {OUT}")


if __name__ == "__main__":
    main()
